<script type='text/javascript' src="<?php printf('%s?d=%d',plugins_url('../js/pac.js',__FILE__ ),time()) ?>"></script>
<div class="wrap">
	<div class="icon32" id="icon-edit"><br></div>
	<?php
		$screen = get_current_screen();
		error_log("adding screen");
		$screen->add_help_tab( array(
		   'id' => 'chessgames-player_mygames',
		   'title' => 'chessgames player help',
		   'content' => 'dan komt hier de help tekst'
		) );
	?>
	<h2 style="color:#014D73;"><?= _e('Mijn Partijen') ?></h2>
	<?php if ( $this->message ) { ?>
			<h3 style="color:#8AC007;">
				<?= $this->message ?>
			</h3>
	<?php } ?>
		<h3 style="color:#93B4C5;">
			Kopieer de code [game id="&lt;ID&gt;"] in je artikel om de partij daar te tonen
		</h3>
	<form method="post" action="?page=chessgames_pgn" id="bor_form_action">
		<p>
			<select name="bor_action">
				<option value="actions"><?= _e('Actions')?></option>
				<option value="delete"><?= _e('Delete')?></option>
			</select>
			<input type="submit" name="bor_form_action_changes"class="button-secondary"value="<?= _e('Apply')?>"/>
			<input type="button" class="button-secondary"value="<?= _e('Voeg een nieuwe partij toe')?>"onclick="window.location='?page=chessgames_pgn'"/><BR>
			<input type="button"class="button-secondary"value="<?= _e('Search')?>"onclick="searchGame()"/>
			<input id="idId" type="text" class="form-control" maxlength="6" size="2" placeholder="<?= _e('id') ?>">
			<input id="pgnId" type="text" class="form-control" placeholder="<?= _e('inhoud') ?>">
			<input type="button"class="button-secondary"value="<?= _e('Next')?>"
				onclick="window.location='?page=chessgames_games&offset=<?php echo $this->offset?$this->offset:0?>'"/>
			<input type="button"class="button-secondary"value="<?= _e('Back')?>"
				onclick="window.location='?page=chessgames_games&back=true&offset=<?php echo $this->offset?$this->offset:0?>'"/>
		</p>

		<table class="widefat page fixed" cellpadding="0">
			<thead>
				<tr>
				<th id="cb" class="manage-column column-cb check-column" style="" scope="col">
					<input type="checkbox"/>
				</th>
					<th class="manage-column"><?= _e('Game ID')?></th>
					<th class="manage-column"><?= _e('Event')?></th>
					<th class="manage-column"><?= _e('Players')?></th>
					<th class="manage-column"><?= _e('Date')?></th>
				</tr>
			</thead>
			<tfoot>
				<tr>
				<th id="cb" class="manage-column column-cb check-column" style="" scope="col">
					<input type="checkbox"/>
				</th>
					<th class="manage-column"><?= _e('Game ID')?></th>
					<th class="manage-column"><?= _e('Event')?></th>
					<th class="manage-column"><?= _e('Players')?></th>
					<th class="manage-column"><?= _e('Date')?></th>
				</tr>
			</tfoot>
			<tbody>
			<?php
				if ( $this->games ) {
					$i = 0;
					foreach ($this->games as $game):
						$i++;
			?>
					<tr class="<?php echo (ceil($i/2) == ($i/2)) ? "" : "alternate"; ?>">
						<th class="check-column" scope="row">
							<input type="checkbox" value="<?= $game->id?>" name="bor_id[]" />
						</th>
						<td>
							<strong><?= $game->id?></strong>
							<div class="row-actions-visible">
							<span class="view">
								<a href="?page=chessgames_pgn&amp;view=<?= $game->id?>">
									View
								</a> |
							</span>
							<span class="edit">
								<a href="?page=chessgames_pgn&amp;id=<?= $game->id?>&amp;edit=true">
									Edit
								</a> |
							</span>
							<span class="delete">
								<a href="?page=chessgames_pgn&amp;delete=<?= $game->id?>"
									onclick="return confirm('Are you sure you want to delete this game?');">
									Delete
								</a>
							</span>
							</div>
						</td>
						<td>
							<?= $game->Event ?></br>
							Round: <?= $game->Round ?>
						</td>
						<td>
							white: <?= $game->White ?></br>
							black: <?= $game->Black ?>
						</td>
						<td>
							<?= $game->GameDate ?></br>
							result: <?= $game->Result ?>
						</td>
					</tr>
			<?php
					endforeach;
				} else {
			?>
					<tr>
						<td colspan="4">
							<?= _e('There are no data.')?>
						</td>
					</tr>
			<?php
				}
			?>
			</tbody>
		</table>
		<p>
			<select name="bor_action-2">
				<option value="actions"><?= _e('Actions')?></option>
				<option value="delete"><?= _e('Delete')?></option>
			</select>
			<input type="submit" name="bor_form_action_changes-2"class="button-secondary" value="<?= _e('Apply')?>"/>
			<input type="button"class="button-secondary"value="<?= _e('Voeg een nieuwe partij toe')?>"onclick="window.location='?page=chessgames_pgn'"/><BR/>
			<input type="button"class="button-secondary"value="<?= _e('Search')?>"onclick="searchGame()"/>
			<input id="idId" type="text" class="form-control" maxlength="6" size="2" placeholder="<?= _e('id') ?>">
			<input id="pgnId" type="text" class="form-control" placeholder="<?= _e('inhoud') ?>">
			<input type="button"class="button-secondary"value="<?= _e('Next')?>"
				onclick="window.location='?page=chessgames_games&offset=<?php echo $this->offset?$this->offset:0?>'"/>
			<input type="button"class="button-secondary"value="<?= _e('Back')?>"
				onclick="window.location='?page=chessgames_games&back=true&offset=<?php echo $this->offset?$this->offset:0?>'"/>
		</p>
	</form>
</div>
